version: 2

updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend-minor-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5

  - package-ecosystem: maven
    directory: /backend
    schedule:
      interval: weekly
    groups:
      backend-minor-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
