# Uso explícito, NÃO é carregado sozinho:
# docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  db:
    restart: unless-stopped

  backend:
    image: ghcr.io/ifpebj-ti/gestao-refeitorio-backend:0.2.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  frontend:
    image: ghcr.io/ifpebj-ti/gestao-refeitorio-frontend:0.2.0
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production