services:
  db:
    restart: unless-stopped

  backend:
    image: ghcr.io/ifpebj-ti/gestao-refeitorio-backend:dev
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: dev

  frontend:
    image: ghcr.io/ifpebj-ti/gestao-refeitorio-frontend:dev
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
