-- Carga inicial dos 58 insumos do catálogo oficial do refeitório
INSERT INTO produtos (id, nome, categoria, unidade_medida, saldo_atual, valor_referencia, controla_validade) VALUES
-- Grãos & Cereais (7 itens)
(gen_random_uuid(), 'Arroz Parboilizado', 'Grãos & Cereais', 'Kg', 0.000, 5.50, TRUE),
(gen_random_uuid(), 'Feijão Carioca', 'Grãos & Cereais', 'Kg', 0.000, 7.80, TRUE),
(gen_random_uuid(), 'Feijão Macassar', 'Grãos & Cereais', 'Kg', 0.000, 7.00, TRUE),
(gen_random_uuid(), 'Macarrão Espaguete', 'Grãos & Cereais', 'Kg', 0.000, 4.20, TRUE),
(gen_random_uuid(), 'Macarrão (Sopa)', 'Grãos & Cereais', 'Kg', 0.000, 4.20, TRUE),
(gen_random_uuid(), 'Flocão de Milho (Cuscuz)', 'Grãos & Cereais', 'Kg', 0.000, 2.80, TRUE),
(gen_random_uuid(), 'Farinha de Mandioca (Farofa)', 'Grãos & Cereais', 'Kg', 0.000, 5.00, TRUE),

-- Proteínas & Frios (8 itens)
(gen_random_uuid(), 'Peito de Frango', 'Proteínas & Frios', 'Kg', 0.000, 18.50, TRUE),
(gen_random_uuid(), 'Coxa de Frango', 'Proteínas & Frios', 'Kg', 0.000, 12.00, TRUE),
(gen_random_uuid(), 'Carne Bovina (Patinho/Moída)', 'Proteínas & Frios', 'Kg', 0.000, 36.00, TRUE),
(gen_random_uuid(), 'Carne Bovina (Acém/Cozido)', 'Proteínas & Frios', 'Kg', 0.000, 29.00, TRUE),
(gen_random_uuid(), 'Charque', 'Proteínas & Frios', 'Kg', 0.000, 42.00, TRUE),
(gen_random_uuid(), 'Linguiça Calabresa', 'Proteínas & Frios', 'Kg', 0.000, 24.00, TRUE),
(gen_random_uuid(), 'Bacon', 'Proteínas & Frios', 'Kg', 0.000, 28.00, TRUE),
(gen_random_uuid(), 'Ovos Pasteurizados / Cartela', 'Proteínas & Frios', 'Und', 0.000, 18.00, TRUE),

-- Hortifrúti (13 itens)
(gen_random_uuid(), 'Abóbora', 'Hortifrúti', 'Kg', 0.000, 3.50, TRUE),
(gen_random_uuid(), 'Alho in natura', 'Hortifrúti', 'Kg', 0.000, 25.00, TRUE),
(gen_random_uuid(), 'Alho triturado', 'Hortifrúti', 'Kg', 0.000, 19.00, TRUE),
(gen_random_uuid(), 'Banana', 'Hortifrúti', 'Kg', 0.000, 4.00, TRUE),
(gen_random_uuid(), 'Batata Inglesa', 'Hortifrúti', 'Kg', 0.000, 6.00, TRUE),
(gen_random_uuid(), 'Beterraba', 'Hortifrúti', 'Kg', 0.000, 4.50, TRUE),
(gen_random_uuid(), 'Cebola', 'Hortifrúti', 'Kg', 0.000, 5.50, TRUE),
(gen_random_uuid(), 'Cebolinha', 'Hortifrúti', 'Maço', 0.000, 2.00, TRUE),
(gen_random_uuid(), 'Cenoura', 'Hortifrúti', 'Kg', 0.000, 5.00, TRUE),
(gen_random_uuid(), 'Coentro', 'Hortifrúti', 'Maço', 0.000, 2.00, TRUE),
(gen_random_uuid(), 'Pimentão', 'Hortifrúti', 'Kg', 0.000, 6.00, TRUE),
(gen_random_uuid(), 'Tomate', 'Hortifrúti', 'Kg', 0.000, 7.00, TRUE),
(gen_random_uuid(), 'Couve', 'Hortifrúti', 'Maço', 0.000, 2.50, TRUE),

-- Laticínios (5 itens)
(gen_random_uuid(), 'Leite in natura', 'Laticínios', 'Lt', 0.000, 4.80, TRUE),
(gen_random_uuid(), 'Creme de Leite', 'Laticínios', 'Und', 0.000, 3.20, TRUE),
(gen_random_uuid(), 'Margarina', 'Laticínios', 'Kg', 0.000, 12.00, TRUE),
(gen_random_uuid(), 'Queijo Mussarela', 'Laticínios', 'Kg', 0.000, 39.00, TRUE),
(gen_random_uuid(), 'Queijo Ralado', 'Laticínios', 'Pct', 0.000, 4.50, TRUE),

-- Especificações & Condimentos (25 itens)
(gen_random_uuid(), 'Açafrão', 'Especificações & Condimentos', 'g', 0.000, 8.00, TRUE),
(gen_random_uuid(), 'Açúcar Cristal', 'Especificações & Condimentos', 'Kg', 0.000, 4.10, TRUE),
(gen_random_uuid(), 'Água Mineral', 'Especificações & Condimentos', 'Lt', 0.000, 1.50, FALSE),
(gen_random_uuid(), 'Amido de Milho', 'Especificações & Condimentos', 'Kg', 0.000, 9.50, TRUE),
(gen_random_uuid(), 'Azeite de Oliva', 'Especificações & Condimentos', 'Lt', 0.000, 38.00, TRUE),
(gen_random_uuid(), 'Biscoito Cream Cracker', 'Especificações & Condimentos', 'Pct', 0.000, 4.00, TRUE),
(gen_random_uuid(), 'Biscoito Maria', 'Especificações & Condimentos', 'Pct', 0.000, 4.00, TRUE),
(gen_random_uuid(), 'Café', 'Especificações & Condimentos', 'Kg', 0.000, 18.00, TRUE),
(gen_random_uuid(), 'Caldo de Carne', 'Especificações & Condimentos', 'Und', 0.000, 1.80, TRUE),
(gen_random_uuid(), 'Caldo de Galinha', 'Especificações & Condimentos', 'Und', 0.000, 1.80, TRUE),
(gen_random_uuid(), 'Coloral', 'Especificações & Condimentos', 'g', 0.000, 5.00, TRUE),
(gen_random_uuid(), 'Cominho', 'Especificações & Condimentos', 'g', 0.000, 6.50, TRUE),
(gen_random_uuid(), 'Ervilha', 'Especificações & Condimentos', 'Lata', 0.000, 3.80, TRUE),
(gen_random_uuid(), 'Extrato de Tomate', 'Especificações & Condimentos', 'Kg', 0.000, 8.50, TRUE),
(gen_random_uuid(), 'Folha de Louro', 'Especificações & Condimentos', 'g', 0.000, 4.00, TRUE),
(gen_random_uuid(), 'Leite de Coco', 'Especificações & Condimentos', 'Vidro', 0.000, 5.20, TRUE),
(gen_random_uuid(), 'Milho Verde', 'Especificações & Condimentos', 'Lata', 0.000, 3.80, TRUE),
(gen_random_uuid(), 'Molho Shoyu', 'Especificações & Condimentos', 'Lt', 0.000, 14.00, TRUE),
(gen_random_uuid(), 'Molho Inglês', 'Especificações & Condimentos', 'Vidro', 0.000, 7.50, TRUE),
(gen_random_uuid(), 'Óleo Vegetal', 'Especificações & Condimentos', 'Lt', 0.000, 6.90, TRUE),
(gen_random_uuid(), 'Orégano', 'Especificações & Condimentos', 'g', 0.000, 6.00, TRUE),
(gen_random_uuid(), 'Pimenta do Reino', 'Especificações & Condimentos', 'g', 0.000, 8.00, TRUE),
(gen_random_uuid(), 'Sal', 'Especificações & Condimentos', 'Kg', 0.000, 2.00, FALSE),
(gen_random_uuid(), 'Vinagre', 'Especificações & Condimentos', 'Lt', 0.000, 3.50, TRUE),
(gen_random_uuid(), 'Azeitona em Conserva', 'Especificações & Condimentos', 'Kg', 0.000, 22.00, TRUE);